#!/bin/sh
# This is an example startup script. Simply edit the line below to provide
# the correct path to the nodules.js file and put this script on your path. You 
# can then start nodules from anywhere.

# set the NODULES_PATH where downloaded modules are stored first
export NODULES_PATH=/path/to/downloaded-modules

node /path/to/lib/nodules.js $1

# I also like to include --debug in the arguments for automatically running with listening for a debugger enabled.